name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Microsoft.Extensions.DependencyInjection.Named/Microsoft.Extensions.DependencyInjection.Named.csproj # Relative to repository root
          # PACKAGE_NAME: NuGet package id, REQUIRED if it's different from project name
          # VERSION_FILE_PATH: Directory.Build.props # Relative to repository root, defaults to project file
          # VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          # VERSION_STATIC: Static version, useful for external providers like Nerdbank.GitVersioning
          # TAG_COMMIT: true # Flag to enable / disable git tagging
          # TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # API key for the NuGet feed
